.zappr.yaml
Using the default zalando compliance settings. The Ticket number is a fake and does not really exist. It is used to comply with the old config (wich exceeds the minimum required zalando config).
=> reconfigure zappr for lumberjack. 

README.md
Documented the need to configure JPA repository scanning. This is needed because we use the `@EnableJpaRepositories` annotation in our library ourselfs. If one would not add here, too, it would scan *only* our package structure for repositories.
Will be made more convenient with  issue #6
=> LBJ-208 Document the need to configure JPA repository scanning

src/main/java/org/zalando/nakadiproducer/eventlog/BusinessEventPayload.java, src/main/java/org/zalando/nakadiproducer/eventlog/EventLogWriter.java, src/main/java/org/zalando/nakadiproducer/eventlog/EventPayload.java, src/main/java/org/zalando/nakadiproducer/eventlog/SimpleEventPayload.java, src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterImpl.java, src/main/java/org/zalando/nakadiproducer/snapshots/SnapshotEventProvider.java, src/main/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotCreationService.java, src/test/java/org/zalando/nakadiproducer/TestApplication.java, src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterTest.java, src/test/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotCreationServiceTest.java, src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmitterIT.java, src/test/java/org/zalando/nakadiproducer/util/Fixture.java
Signature of EventLogWriter changed to accept an event type and a payload. This way we are able to remove the type from inside the payload completely (which makes more sense as it's not part of the data but rather the channel to where we send the data).
EventLog layer untouched. Tests adjusted.
Missing README changes.
=> Extract event type from payload

README.md
Some things (like flowId) were outdated even before this change, some came from the refactoring in #15.
=> Update README for the interface changes.

src/main/java/org/zalando/nakadiproducer/eventlog/EventLogWriter.java
No more "suppose you want". Instead, we add some general text to the interface, and a shorter (hopefully clearer) text for each method.
Part of #15.
=> Simplify the EventLogWriter's javadoc.

README.md, pom.xml, src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java, src/main/resources/db_nakadiproducer/migrations/V1/V1029384757.1.0__schema.sql, src/test/resources/application-test.yml
#4 - up until now, we used the flyway instance that was autoconfigured by spring boot. We therefore shared it with the host application leading to namespace clashes and out of order execution errors. We configure our own Flyway instance now. Since flyway, if configured to use its own schema, automatically creates it if it is missing, i removed the creation script.
Upgraded to the next major release because using the old way to configure the application is not compatible any more. Added a note about upgrade path guarantees to the README.md.
=> #4 better flyway config

README.md, pom.xml, src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java, src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLog.java, src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepository.java, src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterImpl.java, src/main/java/org/zalando/nakadiproducer/snapshots/SnapshotEventProvider.java, src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryIT.java, src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterTest.java, src/test/resources/db/migration/1__application_db_stub.sql
This massively reduces the dependency footprint and solves #5 and #6: No need to configure JpaRepositories and entity scanning in the host application any more. Also removed some more unneccessary pom dependencies.
=> #5 & #6 Migrating from hibernate/jpa to plain spring JdbcTempates

README.md
fahrschein will throw NoClassDefFoundExceptions when used with a jackson version < 2.7.0
=> documenting minimum jackson version

README.md
Mentioning the release notes as source of migration instructions
=> Mentioning the release notes as source of migration instructions

.gitignore
This just adds some eclipse-specific directories to the .gitignore file.
Also it adapts the path of the ignored target directory, as this is now in each subdirectory.
=> MISC: add eclipse-stuff to .gitignore.

nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer/pom.xml, nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/NakadiMetadata.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/TransmissionServiceTest.java, pom.xml
=> #44 flow id sending

README.md, nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/TestApplication.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGeneratorAutoconfigurationIT.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/snapshots/SnapshotEventProviderAutoconfigurationIT.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/util/Fixture.java, nakadi-producer/pom.xml, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/EventLogWriter.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/SimpleSnapshotEventGenerator.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/SimpleSnapshotEventProvider.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/Snapshot.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGenerator.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/SnapshotEventProvider.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotCreationService.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotCreationServiceTest.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/util/Fixture.java, pom.xml
For #42.
- transformed the `SnapshotEventProvider` interface to `SnapshotEventGenerator`, supporting just one event type
- picking up all  `SnapshotEventGenerator` beans from the spring context (thereby supporting multiple event types)
- added a `SimpleSnapshotEventGenerator` to allow using a functional style of defining the Generators
- the original `SnapshotEventProvider` interface is still supported, but marked as deprecated.
(Original:)
- ~~transformed the `SnapshotEventProvider` interface to support just one event type~~
- ~~picking up not just one, but all  `SnapshotEventProvider` beans from the spring context~~
- ~~added a `SimpleSnapshotEventProvider` to allow using a functional Style of defining the Providers~~
=> #42 support multiple snapshot event providers

MAINTAINERS
By Zalando's (internal) OSS checklist, each project needs at least two maintainers.
@BGehrels volunteered.
=> Add @bgehrels to maintainers list.

nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/util/Fixture.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/Snapshot.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGenerator.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotCreationServiceTest.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/util/Fixture.java
Small fixups for previous pull requests (which are not yet released, so this doesn't break anything):
* #49: remove the event type from the new Snapshot class (not the old nested one in the deprecated SnapshotEventProvider, though).
* #51: add a sentence about the behavior id the request body is null to the javadoc.
=> #49/#51 fixups: remove redundant eventtype, javadoc fix

README.md
That fact did cost me at least a full working day (with help from some colleagues).
While writing this comment I noted that the test quoted above this does not work as-is – i.e. the `@Autowired` will only work if you run this with a spring runner. Should we make this test fully working?
=> Mention scheduling disabling for tests

nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java
This was noted when reading the logs produced by this (or rather, when a `grep successfully` didn't find anything).
=> fix typo in log message

nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer/pom.xml, pom.xml
This bumps the versions to 4.1.1 in order to create the next minor release, including the fix #68 for #67.
=> Bump versions to 4.1.1 for #67

nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/EventTransmissionScheduler.java, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryImpl.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/FlywayDataSourceIT.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGenerationWebEndpointIT.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGeneratorAutoconfigurationIT.java
The main AutoConfiguration class had a `@ComponentScan` annotation, causing the whole `org.zalando.nakadiproducer` package (including all subpackages) to be scanned.
This was used only for two beans.
It had the side effect that during tests (which are in the same package), all kinds of @Configuration classes in other tests were also loaded, thereby confusing what each test is actually testing.
This commit removes the `@ComponentScan` annotation at `NakadiProducerAutoConfiguration`, as well as the now superfluous `@Component` and `@Autowired` annotations in `EventTransmissionScheduler` and `EventLogRepositoryImpl`.
It also fixes three tests to load their own configuration explicitly.
It should not change anything in productive behavior (except if some application reuses our package name, …
=> Remove @ComponentScan, @Component, @Autowired

README.md
We had a support request with an empty payload, which turned out to be caused by all properties being private.
=> Mention public getters for data

README.md, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java
This fixes #78.
Work in progress – Not yet tested in a real application (and we don't have any automated tests for this).
In theory, this should be a non-breaking change, so just for a minor version.
For all applications at Zalando (where just `uid` scope is needed), this should save some lines of configuration. For apps working with Nakadi installations which actually needs scopes, nothing should change.
=> Make access-token-scope configuration optional

README.md, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java
This provides a way of avoiding a lot of duplicated configuration, if you are both sending and consuming events. (Fixes #75.)
~~Also document how to not use Fahrschein at all.~~
=> Reuse Fahrschein bean if it already exists (#75).

nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer-starter-spring-boot-2-test/pom.xml, nakadi-producer/pom.xml, pom.xml
Proposed Release notes (feel free to change and adapt):
We now support Spring Boot 2. We will continue to release Spring Boot 1 based versions, too. Their release numbers will be <= 19.x.x (most recent one at the time of this release is 4.2.0).
**Migrating from 4.x to 20.0.0**
- versions >= 20.x will only work with Spring Boot 2
- the Actuator endpoint will be mapped to a different path in Spring Boot 2. Please check [our docs](https://github.com/zalando-nakadi/nakadi-producer-spring-boot-starter/blob/master/README.md) and the [Spring Boot docs](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-custom-mapping) to find the exact path (typically `/actuator/snapshot-event-creation`). Authentication of management …
=> Release 20.0.0

README.md, nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/EnableNakadiProducer.java, nakadi-producer-spring-boot-starter/src/main/resources/META-INF/spring.factories, nakadi-producer-starter-spring-boot-2-test/pom.xml, nakadi-producer-starter-spring-boot-2-test/src/test/java/org/zalando/nakadiproducer/tests/ApplicationIT.java, nakadi-producer-starter-spring-boot-2-test/src/test/java/org/zalando/nakadiproducer/tests/MockNakadiConfig.java, nakadi-producer/pom.xml, pom.xml
Use META-INF/spring.factories to trigger the auto configuration instead of @EnableNakadiProducer
The later had problems with the initialization order in integration tests, as the starters spring configuration has been processed *after* the applications and the tests one.
=> Use META-INF/spring.factories to trigger the auto configuration instead of @EnableNakadiProducer

README.md, nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java, nakadi-producer-starter-spring-boot-2-test/pom.xml, nakadi-producer-starter-spring-boot-2-test/src/main/resources/application.yml, nakadi-producer/pom.xml, pom.xml
Fix #93 Do not require nakadi-producer.access-token-uri anymore
=> Fix #93 Do not require nakadi-producer.access-token-uri anymore

nakadi-producer/pom.xml
This was triggered by an alert from Github:
https://github.com/zalando-nakadi/nakadi-producer-spring-boot-starter/network/alert/nakadi-producer/pom.xml/com.fasterxml.jackson.core:jackson-databind/open
(As I'm not sure how useful this URL will be after I resolve the alert, here the gist of
its content + my interpretation.)
com.fasterxml.jackson.core:jackson-databind was at version 2.8.8, which is affected
by a bunch of remote code execution vulnerabilities:
- CVE-2017-17485
- CVE-2018-7489
- CVE-2017-7525
Versions from 2.8.11 or higher are not affected.
As the dependency version suggested by our parent pom (spring-boot-starter-parent)
is 2.9.6, we can just remove the version number here.
(I don't think the use of Jackson in this library is vulnerable, as
we are not parsing, only creating …
=> Fix Jackson vulnerability

nakadi-producer-starter-spring-boot-2-test/src/main/java/org/zalando/nakadiproducer/tests/Application.java
Previously, in the tests we had each two embedded postgres instances started up,
one as the `embeddedPostgres` bean and one as part of the `dataSource` bean.
(This was visible in the log output, but seemed to not have any other side effects,
apart from maybe making things slower.)
In `@Configuration` classes calling a different bean class to create your bean will
be caught by a proxy and give the existing bean, but our application main class is
not a `@Configuration` class. Instead, we can use a method parameter to inject the
bean created by the other method.
My IDE also removed a superfluous cast in the same class, not sure why it was there.
=> remove duplicated embedded database in our example app

nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer-starter-spring-boot-2-test/pom.xml, nakadi-producer/pom.xml, pom.xml
Bumping version numbers.
This release contains #110 (for #48), #103 (dependency version changes).
(Also some changes to the tests in #107 and #108.)
=> release 20.1.0

CODEOWNERS
The codeowners file used my username from our internal systems, not my github.com one, and thus didn't work.
Not sure how that happened, and was not noticed until now.
=> fix my user name in codeowners file

CODEOWNERS, README.md, nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/flowid/NoopFlowIdComponent.java, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/flowid/TracerFlowIdComponent.java, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotEventCreationEndpoint.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/LockTimeoutIT.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/flowid/TracerFlowIdComponentTest.java, nakadi-producer/pom.xml, nakadi-producer/src/main/java/org/zalando/nakadiproducer/flowid/FlowIdComponent.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/MockNakadiPublishingClient.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java, pom.xml
- Upgraded dependencies to their must current, compatible version (Spring-boot & co, fahrschein, tokens, tracer)
- Had to fix two things, because Spring changed their jar dependency graph:
1. We don't depend on Springs internal MultiValueMap anymore but use Guava instead.
2. Had to explicitly add spring-boot-starter-web, because it has not been implicitly part of actuator anymore
- back ported the automated Trace creation during snapshots (#116)
- back ported the CODEOWNERS file (#91 + #122)
- back ported #120 make lock-timeout configurable
- thought about backporting the performance tests, too, but since [Spring Boot 1 goes End-of-Live 2019-08-01](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019), i don't think we'll have much use for it until then.
- updated the …
=> Backport features from v20

CODEOWNERS, MAINTAINERS, README.md
Benny can't be maintainer anymore.
Florian agreed to become a maintainer (together with Paul, who stays).
This is the final step of #132.
=> Change of maintainer

README.md, nakadi-producer-loadtest/pom.xml, nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryImpl.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryIT.java, nakadi-producer-starter-spring-boot-2-test/pom.xml, nakadi-producer/pom.xml, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/EventLogWriter.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepository.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterImpl.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterTest.java, pom.xml
#140 Persist multiple events in batch
Sketch for the Release notes:
* When you fire multiple similar events at once (in the same transaction), you can now use the plural `fire*Events` methods to store them all in one go into the database, instead of one-by-one. This increases throughput.
* If you used EventLogRepository.persist directly (you shouldn't!), it was previously storing the database ID of the new object back into the EventLog object. This is not happening anymore (in exchange for more efficiency for bulk inserts).
=> #140 Persist multiple events in batch

README.md, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java, nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryImpl.java, nakadi-producer-spring-boot-starter/src/main/resources/db_nakadiproducer/migrations/V2/V2133546886.1.1__add_compaction_key.sql, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/EndToEndTestIT.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryIT.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/CompactionKeyExtractor.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/CompactionKeyExtractors.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/EventLogWriter.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLog.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterImpl.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/NakadiMetadata.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterMultipleTypesTest.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterTest.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventBatcherTest.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java
This is another implementation of #154, where the user can define the compaction key extractors as spring beans, instead of using a register function on the event log writer (as was done in #158).
This seems to be a more spring-y way of doing this.
Doing this also gave the need/opportunity to rewrite the internal logic of finding the right extractor.
~~Opinions please: is this better or worse than the way in #158?~~
(Most of the commits are the same as in #158, the last ones are the new ones.)
For the change log:
----
* #164: support compacted event types (via spring beans)
You now can fire events for a compacted event type, by adding a CompactionKeyExtractor spring bean.
----
=> support compacted event types (#154) via spring beans

README.md
Triggered by a recent question, I've added a table of all the configuration properties.
Also some other tweaks to related documentation.
=> README: document spring properties together

nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryImpl.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryIT.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepository.java, nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java, nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java
* repository: add batch deletion method to interface (with default implementation)
* repository: implement batch deletion (uses updateBatch)
* test for batch deletion
* ~repository: refactoring for persist~
* transmission: use batch deletion
This came up as a part of #170, but seems useful enough without it, so I'm submitting this as a separate PR.
=> Batch deletion of eventlogs

nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/eventlog/impl/batcher/QueryStatementBatcher.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/eventlog/impl/batcher/QueryStatementBatcherIT.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/eventlog/impl/batcher/QueryStatementBatcherTest.java
This allows to fake batches for statements returning data. Not yet used in the rest of the code, that will be added in later commits.
(This came up as part of #170.)
JDBC distinguishes between "queries" (which can return results) and "updates" (which only can return a number of affected rows). Only for updates you can use the batching feature of JDBC (i.e. sending multiple statements together to the server to have them executed together, saving the round trips to the DB and back). This is then also reflected in Spring's JdbcTemplate (and NamedParameterJdbcTemplate).
As we want to return the auto-generated ID from the inserted rows, the "batching" feature won't work for us.
Searching in the WWW, I found [Batching Select Statements in …
=> Add a QueryStatementBatcher

nakadi-producer-spring-boot-starter/src/main/resources/db_nakadiproducer/migrations/V2/V2133546886.1.2__grant_delete_permissions.sql
Without this, an application user who is not owner of the database/table (or superuser) can't delete events after sending them out.
Fixes #101.
I just stumbled over this in my PoC application for #170, and then found this issue from 5 years ago.
=> Add DELETE permission to the eventlog table.

nakadi-producer-spring-boot-starter/pom.xml, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/FlywayDataSourceIT.java, nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/config/EmbeddedDataSourceConfig.java
This allows to use a newer postgresql version without much other changes.
The otj-pg-embedded 0.7.1 was using postgresql 9.5, which is outdated for several years, and doesn't know `CREATE PUBLICATION` (which I wanted to add to #174).
Current versions of otj-pg-embedded use docker images, which I didn't want to go into.
=> use Zonky embedded postgres instead of opentable one for tests.

nakadi-producer-starter-spring-boot-2-test/pom.xml
This prevents Maven from trying to dynamically fetch a transitive dependency each time.
This always broke the build when my VPN was not enabled.
=> spring-boot-2-test: add a fixed version of junit4.
