README.md

Mainly grammar/spelling, some links added.

Some small README fixes.

---

pom.xml

Fixing the version in the pom and configuring the maven central repository

Preparations for Release 1.0

---

README.md
pom.xml
src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java

Bugfix to avoid ClassNotFound/NoClassDefFound errors and duplicate bean instantiations (NoopFlowIdComponent was always initialized even if the Tracer Bean existed.

Lbj 208 fix optional dependencies

---

README.md

EventPayloadImpl has been renamed to SimpleEventPayload

LBJ-208 Fix the changed class name in the docs

---

README.md

This helps handling out of order messages

LBJ-208 document, that the event id is monotonically increasing

---

pom.xml

Releasing v. 3.0.0 of the Library

Releasing v. 3.0.0

---

README.md

Spring Data JPA has been replaced with Spring JDBC

Spring Data JPA has been replaced with Spring JDBC

---

pom.xml
src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java

#27 do not instantiate the accessTokenProvider when in mock mode

---

nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer/pom.xml
pom.xml

releasing 4.0.0 and use a common parent pom from both components

releasing 4.0.0

---

nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer/pom.xml
pom.xml

The parent pom needs its own distribution management, so I pulled it up to the parent.

pull up distribution management to the parent pom

---

pom.xml

by adding the missing gpg/staging plugins

making the parent pom deployable to maven central

---

nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer/pom.xml
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/MockNakadiPublishingClient.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/MockNakadiPublishingClientTest.java
pom.xml

Fixed #40: NPE in MockNakadiPublishingClient

Fixed #40: NPE in MockNakadiPublishingClient

---

nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java

- Implemented @ePaul s review comment from #46 
- Renamed the test class to match the name of the class under test

Fixed #44: writing an assert more clearly

---

README.md
nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotEventCreationEndpoint.java
nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotEventCreationMvcEndpoint.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGenerationWebEndpointIT.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGeneratorAutoconfigurationIT.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/SimpleSnapshotEventGenerator.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGenerator.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotCreationService.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/snapshots/impl/SnapshotCreationServiceTest.java

Fixes #43.
Not yet tested ... I'll need to plug this into a real-live application first, or write a test one.

Add filtering to snapshot event generation mechanism.

---

README.md

Added a link to a list of "issues that should be easy to contribute" to the readme.md

Added a link to a list of "issues that should be easy to contribute"

---

CONTRIBUTING.md
README.md

First draft. Please have a look – what am I missing here?

First draft of a contribution guide

---

README.md

Why does it exist? Framed the project for the potential user.

Better introduction in readme

---

CONTRIBUTING.md

Since we do not follow a particular standard, looking around and getting a feeling of the existing code should be enough for now. If we experience particular recurring errors, we can still add them here.

Contribution Guidelines: Added a section on code style

---

nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java
nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/flowid/NoopFlowIdComponent.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/FlywayDataSourceIT.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/NakadiProducerFlywayCallbackIT.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/NonNakadiProducerFlywayCallbackIT.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/flowid/TracerFlowIdComponentTest.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGenerationWebEndpointIT.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/snapshots/SnapshotEventGeneratorAutoconfigurationIT.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/eventlog/impl/DataChangeEventEnvelope.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/MockNakadiPublishingClientTest.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java

Those were found by Codacy: https://www.codacy.com/app/ePaul/nakadi-producer-spring-boot-starter/issues

Fix some code quality issues

---

nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/LockingIT.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java

#67 - do not send events when their lock expired

---

nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer/pom.xml
pom.xml

This bumps the version number so we can release the next version.

Version bump to 4.1.2 (for #37)

---

nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer/pom.xml
pom.xml

Preparing for Release 4.1.3, containing PR #82 for #78, as well as #76.

Bump versions 4.1.2 → 4.1.3

---

nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer/pom.xml
pom.xml

bump version 4.1.3 → 4.2.0

---

README.md

Also streamlined the text a bit, since it has become quite long and a bit unstructured already

Documented how to run the library in a k8s environment.

---

nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java
nakadi-producer-starter-spring-boot-2-test/pom.xml
nakadi-producer/pom.xml
pom.xml

Fix #92 - Submission to Nakadi does not work without @EnableScheduling

Fix #92 - Submission to Nakadi does not work without @EnableScheduling

---

nakadi-producer-starter-spring-boot-2-test/src/test/java/org/zalando/nakadiproducer/tests/ApplicationIT.java

The test previously only tested whether the snapshot endpoint could be called, not whether actually any events were created or submitted.
I added the mock client in the test and checked that it actually go two events.

add asserts to ApplicationIT

---

nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/LockingIT.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/MockNakadiPublishingClient.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventBatcher.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmitter.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterTest.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/MockNakadiPublishingClientTest.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventBatcherTest.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java

#48 implement batching

---

nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/LockingIT.java
nakadi-producer/pom.xml
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/MockNakadiPublishingClient.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventBatcher.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmitter.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/eventlog/impl/EventLogWriterTest.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/MockNakadiPublishingClientTest.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventBatcherTest.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java
pom.xml

A copy of #110, implementing #48, for the spring-boot-1 branch.
Also includes the version update for releasing 4.3.0.

Batch event submission (#48)

---

nakadi-producer-starter-spring-boot-2-test/pom.xml

#116: version bump the tests, too

---

README.md
nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/LockTimeoutIT.java
nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java
nakadi-producer/src/test/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionServiceTest.java

#120 make lock-timeout configurable

#120 make lock-timeout configurable

---

README.md

Fix a mistyped spring annotation

Fix a mistyped spring annotation

---

README.md

fix a misspelled Spring annotation

fix a misspelled Spring annotation

---

nakadi-producer-loadtest/pom.xml
nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer-starter-spring-boot-2-test/pom.xml
nakadi-producer/pom.xml
pom.xml

Bump versions to 20.3.0

---

nakadi-producer/src/main/java/org/zalando/nakadiproducer/transmission/impl/EventTransmissionService.java

To understand the issue better when the exception occurs during the publishing of the events

log the exception

---

nakadi-producer-loadtest/pom.xml
nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer-starter-spring-boot-2-test/pom.xml
nakadi-producer/pom.xml
pom.xml

Version bump for the next release (after merging #128).

Bump versions for 20.3.1

---

README.md

This was noted in a private chat with a user.

Mention compaction problems in README, link guidelines

---

.travis.yml

#134 travis ci builds are broken

---

SECURITY.md

#136 update SECURITY.md

---

README.md
nakadi-producer-spring-boot-starter/pom.xml
nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/NakadiProducerAutoConfiguration.java
nakadi-producer-spring-boot-starter/src/main/java/org/zalando/nakadiproducer/eventlog/impl/EventLogRepositoryImpl.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/EventLockSizeConfiguredIT.java
nakadi-producer-spring-boot-starter/src/test/java/org/zalando/nakadiproducer/EventLockSizeDefaultIT.java
nakadi-producer/pom.xml
pom.xml

This is a back-port of #152 for #112 to the spring-boot-1 branch.

Do not lock all available events (#112)
